name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          go-version: 1.17

      - name: install
        run: pip install -r requirements.txt

      - name: Test
        run: python -m unittest -s discover tests

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: girikuncoro/belajar-cicd:latest
      - name: Build and Push Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-cd-practice:${{ github.sha }} && echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin && docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-practice:${{ github.sha }}
